services:
  gseek-bot:
    build:
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./logs:/app/logs
    stop_signal: SIGINT
    restart: unless-stopped
    entrypoint: [ ".venv/bin/python", "-m", "app.main" ]
    networks:
      - my_docker_network
  # mongo:
  #   image: mongo:8.0
  #   restart: unless-stopped
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - ./mongodb/data:/data/db
  #   networks:
  #     - my_docker_network

networks:
  my_docker_network:
    external: true
