services:
  bot:
    build:
      dockerfile: ./Dockerfile
    environment:
      MONGO__HOST: mongo
      MONGO__PORT: 27017
      MONGO__USER: ку
      MONGO__PASSWORD: свiт
      MONGO__NAME: gseek-bot
    env_file: .env
    volumes:
      - bot_data:/data
    restart: unless-stopped
  mongo:
    image: mongo:4 # mongo 5+ doesnt support CPU without AVX
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ку
      MONGO_INITDB_ROOT_PASSWORD: свiт
    volumes:
      - mongo_data:/data/db

volumes:
  bot_data:
  mongo_data:

